USE [BookKeeperDB_Test]
GO

/****** Object:  Table [dbo].[user_book]    Script Date: 8/27/2024 3:38:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[user_book](
	[USER_ID] [int] NOT NULL,
	[BOOK_ID] [int] NOT NULL,
 CONSTRAINT [PK_USER_BOOK] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC,
	[BOOK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[user_book]  WITH CHECK ADD  CONSTRAINT [FK_USER_BOOK_BOOK] FOREIGN KEY([BOOK_ID])
REFERENCES [dbo].[book] ([BOOK_ID])
GO

ALTER TABLE [dbo].[user_book] CHECK CONSTRAINT [FK_USER_BOOK_BOOK]
GO

ALTER TABLE [dbo].[user_book]  WITH CHECK ADD  CONSTRAINT [FK_USER_BOOK_user] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[user] ([USER_ID])
GO

ALTER TABLE [dbo].[user_book] CHECK CONSTRAINT [FK_USER_BOOK_user]
GO

