USE [BookKeeperDB_Test]
GO

/****** Object:  Table [dbo].[review]    Script Date: 8/27/2024 3:38:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[review](
	[BOOK_ID] [int] NOT NULL,
	[USER_ID] [int] NOT NULL,
	[DESCRIPTION] [nvarchar](max) NULL,
	[RATING] [int] NOT NULL,
	[DATE_SUBMITTED] [date] NOT NULL,
 CONSTRAINT [PK_review_1] PRIMARY KEY CLUSTERED 
(
	[BOOK_ID] ASC,
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[review]  WITH CHECK ADD  CONSTRAINT [FK_review_book] FOREIGN KEY([BOOK_ID])
REFERENCES [dbo].[book] ([BOOK_ID])
GO

ALTER TABLE [dbo].[review] CHECK CONSTRAINT [FK_review_book]
GO

ALTER TABLE [dbo].[review]  WITH CHECK ADD  CONSTRAINT [FK_review_user] FOREIGN KEY([USER_ID])
REFERENCES [dbo].[user] ([USER_ID])
GO

ALTER TABLE [dbo].[review] CHECK CONSTRAINT [FK_review_user]
GO

