USE [BookKeeperDB_Test]
GO

/****** Object:  Table [dbo].[user]    Script Date: 8/27/2024 3:38:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[user](
	[USER_ID] [int] IDENTITY(1,1) NOT NULL,
	[IDENTIFICATION_ID] [nvarchar](450) NOT NULL,
	[USERNAME] [nvarchar](max) NOT NULL,
	[DESCRIPTION] [nvarchar](max) NOT NULL,
	[DATE_JOINED] [date] NOT NULL,
	[PROFILE_PICTURE] [nvarchar](max) NULL,
 CONSTRAINT [PK_user] PRIMARY KEY CLUSTERED 
(
	[USER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[user]  WITH CHECK ADD  CONSTRAINT [FK_user_AspNetUsers] FOREIGN KEY([IDENTIFICATION_ID])
REFERENCES [dbo].[AspNetUsers] ([Id])
GO

ALTER TABLE [dbo].[user] CHECK CONSTRAINT [FK_user_AspNetUsers]
GO

