USE [BookKeeperDB_Test]
GO

/****** Object:  Table [dbo].[book]    Script Date: 8/27/2024 3:37:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[book](
	[BOOK_ID] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [nvarchar](max) NOT NULL,
	[PAGES] [int] NOT NULL,
	[ISBN] [nvarchar](max) NOT NULL,
	[COVER_PICTURE] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_book] PRIMARY KEY CLUSTERED 
(
	[BOOK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

